
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action ApplicationAction;
	private global::Gtk.Action quitAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.MenuBar menubar2;
	private global::Gtk.Frame frame1;
	private global::Gtk.Alignment GtkAlignment;
	private global::Gtk.Table table1;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.Label label4;
	private global::Gtk.Label label5;
	private global::Gtk.Button loadButton;
	private global::Gtk.Entry std_isin;
	private global::Gtk.ComboBox std_typ;
	private global::Gtk.ComboBoxEntry std_wertpapier;
	private global::BoersenApp.ValidatedEntry std_wkn;
	private global::Gtk.Label GtkLabel2;
	private global::Gtk.Notebook typ;
	private global::Gtk.Frame frame2;
	private global::Gtk.Alignment GtkAlignment1;
	private global::Gtk.Table table2;
	private global::BoersenApp.ValidatedEntry discount_bezug;
	private global::BoersenApp.ValidatedEntry discount_cap;
	private global::BoersenApp.ValidatedEntry discount_lfz;
	private global::Gtk.Label label21;
	private global::Gtk.Label label3;
	private global::Gtk.Label label6;
	private global::Gtk.Label GtkLabel4;
	private global::Gtk.Label label7;
	private global::Gtk.Frame frame3;
	private global::Gtk.Alignment GtkAlignment2;
	private global::Gtk.Table table3;
	private global::Gtk.Entry entry6;
	private global::Gtk.Entry entry7;
	private global::Gtk.Label label10;
	private global::Gtk.Label label11;
	private global::Gtk.Label label9;
	private global::Gtk.Label GtkLabel5;
	private global::Gtk.Label label8;
	private global::Gtk.HSeparator hseparator1;
	private global::Gtk.Frame frame4;
	private global::Gtk.Alignment GtkAlignment3;
	private global::Gtk.Table table4;
	private global::Gtk.Label label12;
	private global::Gtk.Label label13;
	private global::Gtk.Label label20;
	private global::BoersenApp.ValidatedEntry szenario_base;
	private global::BoersenApp.ValidatedEntry szenario_end;
	private global::Gtk.HScale szenario_endscale;
	private global::BoersenApp.ValidatedEntry szenario_kauf;
	private global::Gtk.Label GtkLabel3;
	private global::Gtk.Frame frame5;
	private global::Gtk.Alignment GtkAlignment4;
	private global::Gtk.VBox vbox2;
	private global::Gtk.Table table5;
	private global::Gtk.Label Interest;
	private global::Gtk.Label InterestPA;
	private global::Gtk.Label label14;
	private global::Gtk.Label label15;
	private global::Gtk.Label label16;
	private global::Gtk.Label PayBack;
	private global::Gtk.DrawingArea drawingarea1;
	private global::Gtk.Label GtkLabel6;
	private global::Gtk.Statusbar statusbar1;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.ApplicationAction = new global::Gtk.Action ("ApplicationAction", global::Mono.Unix.Catalog.GetString ("Application"), null, null);
		this.ApplicationAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Application");
		w1.Add (this.ApplicationAction, null);
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.quitAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='ApplicationAction' action='ApplicationAction'><menuitem name='quitAction' action='quitAction'/></menu></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame1 = new global::Gtk.Frame ();
		this.frame1.Name = "frame1";
		this.frame1.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame1.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(3)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Wertpapier");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Typ");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
		w4.TopAttach = ((uint)(3));
		w4.BottomAttach = ((uint)(4));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("WKN");
		this.table1.Add (this.label4);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.label4]));
		w5.TopAttach = ((uint)(1));
		w5.BottomAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("ISIN");
		this.table1.Add (this.label5);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1 [this.label5]));
		w6.TopAttach = ((uint)(2));
		w6.BottomAttach = ((uint)(3));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.loadButton = new global::Gtk.Button ();
		this.loadButton.CanFocus = true;
		this.loadButton.Name = "loadButton";
		this.loadButton.UseUnderline = true;
		// Container child loadButton.Gtk.Container+ContainerChild
		global::Gtk.Alignment w7 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		global::Gtk.HBox w8 = new global::Gtk.HBox ();
		w8.Spacing = 2;
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Image w9 = new global::Gtk.Image ();
		w9.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_search", global::Gtk.IconSize.Menu);
		w8.Add (w9);
		// Container child GtkHBox.Gtk.Container+ContainerChild
		global::Gtk.Label w11 = new global::Gtk.Label ();
		w11.LabelProp = global::Mono.Unix.Catalog.GetString ("_Laden");
		w11.UseUnderline = true;
		w8.Add (w11);
		w7.Add (w8);
		this.loadButton.Add (w7);
		this.table1.Add (this.loadButton);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1 [this.loadButton]));
		w15.LeftAttach = ((uint)(2));
		w15.RightAttach = ((uint)(3));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.std_isin = new global::Gtk.Entry ();
		this.std_isin.CanFocus = true;
		this.std_isin.Name = "std_isin";
		this.std_isin.Text = global::Mono.Unix.Catalog.GetString ("DE000GT443X6");
		this.std_isin.IsEditable = true;
		this.std_isin.InvisibleChar = '●';
		this.table1.Add (this.std_isin);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1 [this.std_isin]));
		w16.TopAttach = ((uint)(2));
		w16.BottomAttach = ((uint)(3));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.std_typ = global::Gtk.ComboBox.NewText ();
		this.std_typ.AppendText (global::Mono.Unix.Catalog.GetString ("Discountzertifikat"));
		this.std_typ.AppendText (global::Mono.Unix.Catalog.GetString ("Expresszertifikat"));
		this.std_typ.Sensitive = false;
		this.std_typ.Name = "std_typ";
		this.std_typ.Active = 0;
		this.table1.Add (this.std_typ);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1 [this.std_typ]));
		w17.TopAttach = ((uint)(3));
		w17.BottomAttach = ((uint)(4));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.std_wertpapier = global::Gtk.ComboBoxEntry.NewText ();
		this.std_wertpapier.AppendText (global::Mono.Unix.Catalog.GetString ("Goldman Sachs Wertpapier GmbH DISC.Z 15.09.14 DAX 8000"));
		this.std_wertpapier.Name = "std_wertpapier";
		this.std_wertpapier.Active = 0;
		this.table1.Add (this.std_wertpapier);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.std_wertpapier]));
		w18.LeftAttach = ((uint)(1));
		w18.RightAttach = ((uint)(2));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.std_wkn = new global::BoersenApp.ValidatedEntry ();
		this.std_wkn.CanFocus = true;
		this.std_wkn.Name = "std_wkn";
		this.std_wkn.Text = global::Mono.Unix.Catalog.GetString ("GT443X");
		this.std_wkn.IsEditable = true;
		this.std_wkn.InvisibleChar = '●';
		this.table1.Add (this.std_wkn);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.std_wkn]));
		w19.TopAttach = ((uint)(1));
		w19.BottomAttach = ((uint)(2));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment.Add (this.table1);
		this.frame1.Add (this.GtkAlignment);
		this.GtkLabel2 = new global::Gtk.Label ();
		this.GtkLabel2.Name = "GtkLabel2";
		this.GtkLabel2.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Stammdaten</b>");
		this.GtkLabel2.UseMarkup = true;
		this.frame1.LabelWidget = this.GtkLabel2;
		this.vbox1.Add (this.frame1);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame1]));
		w22.Position = 1;
		w22.Expand = false;
		w22.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.typ = new global::Gtk.Notebook ();
		this.typ.CanFocus = true;
		this.typ.Name = "typ";
		this.typ.CurrentPage = 0;
		this.typ.ShowBorder = false;
		this.typ.ShowTabs = false;
		// Container child typ.Gtk.Notebook+NotebookChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.table2 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.table2.Name = "table2";
		this.table2.RowSpacing = ((uint)(6));
		this.table2.ColumnSpacing = ((uint)(6));
		// Container child table2.Gtk.Table+TableChild
		this.discount_bezug = new global::BoersenApp.ValidatedEntry ();
		this.discount_bezug.CanFocus = true;
		this.discount_bezug.Name = "discount_bezug";
		this.discount_bezug.Text = global::Mono.Unix.Catalog.GetString ("0,01");
		this.discount_bezug.IsEditable = true;
		this.discount_bezug.InvisibleChar = '●';
		this.table2.Add (this.discount_bezug);
		global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.table2 [this.discount_bezug]));
		w23.TopAttach = ((uint)(2));
		w23.BottomAttach = ((uint)(3));
		w23.LeftAttach = ((uint)(1));
		w23.RightAttach = ((uint)(2));
		w23.XOptions = ((global::Gtk.AttachOptions)(4));
		w23.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.discount_cap = new global::BoersenApp.ValidatedEntry ();
		this.discount_cap.CanFocus = true;
		this.discount_cap.Name = "discount_cap";
		this.discount_cap.Text = global::Mono.Unix.Catalog.GetString ("8.000,00");
		this.discount_cap.IsEditable = true;
		this.discount_cap.InvisibleChar = '●';
		this.table2.Add (this.discount_cap);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table2 [this.discount_cap]));
		w24.TopAttach = ((uint)(1));
		w24.BottomAttach = ((uint)(2));
		w24.LeftAttach = ((uint)(1));
		w24.RightAttach = ((uint)(2));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.discount_lfz = new global::BoersenApp.ValidatedEntry ();
		this.discount_lfz.CanFocus = true;
		this.discount_lfz.Name = "discount_lfz";
		this.discount_lfz.Text = global::Mono.Unix.Catalog.GetString ("10.09.2014");
		this.discount_lfz.IsEditable = true;
		this.discount_lfz.InvisibleChar = '●';
		this.table2.Add (this.discount_lfz);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table2 [this.discount_lfz]));
		w25.LeftAttach = ((uint)(1));
		w25.RightAttach = ((uint)(2));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label21 = new global::Gtk.Label ();
		this.label21.Name = "label21";
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Bezugsverhaeltnis");
		this.table2.Add (this.label21);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table2 [this.label21]));
		w26.TopAttach = ((uint)(2));
		w26.BottomAttach = ((uint)(3));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Faelligkeit");
		this.table2.Add (this.label3);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table2 [this.label3]));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table2.Gtk.Table+TableChild
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Cap");
		this.table2.Add (this.label6);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table2 [this.label6]));
		w28.TopAttach = ((uint)(1));
		w28.BottomAttach = ((uint)(2));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment1.Add (this.table2);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel4 = new global::Gtk.Label ();
		this.GtkLabel4.Name = "GtkLabel4";
		this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Discountzertifikat</b>");
		this.GtkLabel4.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel4;
		this.typ.Add (this.frame2);
		// Notebook tab
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Discountzertifikat");
		this.typ.SetTabLabel (this.frame2, this.label7);
		this.label7.ShowAll ();
		// Container child typ.Gtk.Notebook+NotebookChild
		this.frame3 = new global::Gtk.Frame ();
		this.frame3.Name = "frame3";
		this.frame3.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame3.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.entry6 = new global::Gtk.Entry ();
		this.entry6.CanFocus = true;
		this.entry6.Name = "entry6";
		this.entry6.IsEditable = true;
		this.entry6.InvisibleChar = '●';
		this.table3.Add (this.entry6);
		global::Gtk.Table.TableChild w32 = ((global::Gtk.Table.TableChild)(this.table3 [this.entry6]));
		w32.LeftAttach = ((uint)(1));
		w32.RightAttach = ((uint)(2));
		w32.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.entry7 = new global::Gtk.Entry ();
		this.entry7.CanFocus = true;
		this.entry7.Name = "entry7";
		this.entry7.IsEditable = true;
		this.entry7.InvisibleChar = '●';
		this.table3.Add (this.entry7);
		global::Gtk.Table.TableChild w33 = ((global::Gtk.Table.TableChild)(this.table3 [this.entry7]));
		w33.TopAttach = ((uint)(1));
		w33.BottomAttach = ((uint)(2));
		w33.LeftAttach = ((uint)(1));
		w33.RightAttach = ((uint)(2));
		w33.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Cap");
		this.table3.Add (this.label10);
		global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table3 [this.label10]));
		w34.TopAttach = ((uint)(1));
		w34.BottomAttach = ((uint)(2));
		w34.XOptions = ((global::Gtk.AttachOptions)(4));
		w34.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label11 = new global::Gtk.Label ();
		this.label11.Name = "label11";
		this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Rueckzahlplan");
		this.table3.Add (this.label11);
		global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table3 [this.label11]));
		w35.TopAttach = ((uint)(2));
		w35.BottomAttach = ((uint)(3));
		w35.XOptions = ((global::Gtk.AttachOptions)(4));
		w35.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Laufzeit");
		this.table3.Add (this.label9);
		global::Gtk.Table.TableChild w36 = ((global::Gtk.Table.TableChild)(this.table3 [this.label9]));
		w36.XOptions = ((global::Gtk.AttachOptions)(4));
		w36.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment2.Add (this.table3);
		this.frame3.Add (this.GtkAlignment2);
		this.GtkLabel5 = new global::Gtk.Label ();
		this.GtkLabel5.Name = "GtkLabel5";
		this.GtkLabel5.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Expresszertifikat</b>");
		this.GtkLabel5.UseMarkup = true;
		this.frame3.LabelWidget = this.GtkLabel5;
		this.typ.Add (this.frame3);
		global::Gtk.Notebook.NotebookChild w39 = ((global::Gtk.Notebook.NotebookChild)(this.typ [this.frame3]));
		w39.Position = 1;
		// Notebook tab
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Expresszertifikat");
		this.typ.SetTabLabel (this.frame3, this.label8);
		this.label8.ShowAll ();
		this.vbox1.Add (this.typ);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.typ]));
		w40.Position = 2;
		w40.Expand = false;
		w40.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hseparator1 = new global::Gtk.HSeparator ();
		this.hseparator1.Name = "hseparator1";
		this.vbox1.Add (this.hseparator1);
		global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hseparator1]));
		w41.Position = 3;
		w41.Expand = false;
		w41.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.table4 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
		this.table4.Name = "table4";
		this.table4.RowSpacing = ((uint)(6));
		this.table4.ColumnSpacing = ((uint)(6));
		// Container child table4.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Kaufkurs");
		this.table4.Add (this.label12);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table4 [this.label12]));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Kurs Basiswert");
		this.table4.Add (this.label13);
		global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table4 [this.label13]));
		w43.TopAttach = ((uint)(1));
		w43.BottomAttach = ((uint)(2));
		w43.XOptions = ((global::Gtk.AttachOptions)(4));
		w43.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.label20 = new global::Gtk.Label ();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Endkurs Basiswert");
		this.table4.Add (this.label20);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table4 [this.label20]));
		w44.TopAttach = ((uint)(2));
		w44.BottomAttach = ((uint)(3));
		w44.XOptions = ((global::Gtk.AttachOptions)(4));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.szenario_base = new global::BoersenApp.ValidatedEntry ();
		this.szenario_base.CanFocus = true;
		this.szenario_base.Name = "szenario_base";
		this.szenario_base.Text = global::Mono.Unix.Catalog.GetString ("8.426,82");
		this.szenario_base.IsEditable = true;
		this.szenario_base.InvisibleChar = '●';
		this.table4.Add (this.szenario_base);
		global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table4 [this.szenario_base]));
		w45.TopAttach = ((uint)(1));
		w45.BottomAttach = ((uint)(2));
		w45.LeftAttach = ((uint)(1));
		w45.RightAttach = ((uint)(2));
		w45.XOptions = ((global::Gtk.AttachOptions)(4));
		w45.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.szenario_end = new global::BoersenApp.ValidatedEntry ();
		this.szenario_end.CanFocus = true;
		this.szenario_end.Name = "szenario_end";
		this.szenario_end.Text = global::Mono.Unix.Catalog.GetString ("8.426,82");
		this.szenario_end.IsEditable = true;
		this.szenario_end.InvisibleChar = '●';
		this.table4.Add (this.szenario_end);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table4 [this.szenario_end]));
		w46.TopAttach = ((uint)(2));
		w46.BottomAttach = ((uint)(3));
		w46.LeftAttach = ((uint)(1));
		w46.RightAttach = ((uint)(2));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.szenario_endscale = new global::Gtk.HScale (null);
		this.szenario_endscale.CanFocus = true;
		this.szenario_endscale.Name = "szenario_endscale";
		this.szenario_endscale.Adjustment.Lower = 80;
		this.szenario_endscale.Adjustment.Upper = 120;
		this.szenario_endscale.Adjustment.PageIncrement = 10;
		this.szenario_endscale.Adjustment.StepIncrement = 1;
		this.szenario_endscale.Adjustment.Value = 100;
		this.szenario_endscale.DrawValue = false;
		this.szenario_endscale.Digits = 0;
		this.szenario_endscale.ValuePos = ((global::Gtk.PositionType)(2));
		this.table4.Add (this.szenario_endscale);
		global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table4 [this.szenario_endscale]));
		w47.TopAttach = ((uint)(2));
		w47.BottomAttach = ((uint)(3));
		w47.LeftAttach = ((uint)(2));
		w47.RightAttach = ((uint)(3));
		w47.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table4.Gtk.Table+TableChild
		this.szenario_kauf = new global::BoersenApp.ValidatedEntry ();
		this.szenario_kauf.CanFocus = true;
		this.szenario_kauf.Name = "szenario_kauf";
		this.szenario_kauf.Text = global::Mono.Unix.Catalog.GetString ("75,080");
		this.szenario_kauf.IsEditable = true;
		this.szenario_kauf.InvisibleChar = '●';
		this.table4.Add (this.szenario_kauf);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table4 [this.szenario_kauf]));
		w48.LeftAttach = ((uint)(1));
		w48.RightAttach = ((uint)(2));
		w48.XOptions = ((global::Gtk.AttachOptions)(4));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment3.Add (this.table4);
		this.frame4.Add (this.GtkAlignment3);
		this.GtkLabel3 = new global::Gtk.Label ();
		this.GtkLabel3.Name = "GtkLabel3";
		this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Szenario</b>");
		this.GtkLabel3.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel3;
		this.vbox1.Add (this.frame4);
		global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame4]));
		w51.Position = 4;
		w51.Expand = false;
		w51.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame ();
		this.frame5.Name = "frame5";
		this.frame5.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment4 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment4.Name = "GtkAlignment4";
		this.GtkAlignment4.LeftPadding = ((uint)(12));
		// Container child GtkAlignment4.Gtk.Container+ContainerChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.table5 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.table5.Name = "table5";
		this.table5.RowSpacing = ((uint)(6));
		this.table5.ColumnSpacing = ((uint)(6));
		// Container child table5.Gtk.Table+TableChild
		this.Interest = new global::Gtk.Label ();
		this.Interest.Name = "Interest";
		this.Interest.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"green\" size=\"x-large\">2,00 %</span>");
		this.Interest.UseMarkup = true;
		this.table5.Add (this.Interest);
		global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table5 [this.Interest]));
		w52.TopAttach = ((uint)(1));
		w52.BottomAttach = ((uint)(2));
		w52.LeftAttach = ((uint)(1));
		w52.RightAttach = ((uint)(2));
		w52.XOptions = ((global::Gtk.AttachOptions)(4));
		w52.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.InterestPA = new global::Gtk.Label ();
		this.InterestPA.Name = "InterestPA";
		this.InterestPA.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"green\" size=\"x-large\">1,58 %</span>");
		this.InterestPA.UseMarkup = true;
		this.table5.Add (this.InterestPA);
		global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table5 [this.InterestPA]));
		w53.TopAttach = ((uint)(2));
		w53.BottomAttach = ((uint)(3));
		w53.LeftAttach = ((uint)(1));
		w53.RightAttach = ((uint)(2));
		w53.XOptions = ((global::Gtk.AttachOptions)(4));
		w53.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Rückzahlung");
		this.label14.UseMarkup = true;
		this.table5.Add (this.label14);
		global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table5 [this.label14]));
		w54.XOptions = ((global::Gtk.AttachOptions)(4));
		w54.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Rendite");
		this.table5.Add (this.label15);
		global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table5 [this.label15]));
		w55.TopAttach = ((uint)(1));
		w55.BottomAttach = ((uint)(2));
		w55.XOptions = ((global::Gtk.AttachOptions)(4));
		w55.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Rendite p.A.");
		this.table5.Add (this.label16);
		global::Gtk.Table.TableChild w56 = ((global::Gtk.Table.TableChild)(this.table5 [this.label16]));
		w56.TopAttach = ((uint)(2));
		w56.BottomAttach = ((uint)(3));
		w56.XOptions = ((global::Gtk.AttachOptions)(4));
		w56.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.PayBack = new global::Gtk.Label ();
		this.PayBack.Name = "PayBack";
		this.PayBack.LabelProp = global::Mono.Unix.Catalog.GetString ("<span color=\"red\" size=\"x-large\">10,00</span>");
		this.PayBack.UseMarkup = true;
		this.table5.Add (this.PayBack);
		global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.table5 [this.PayBack]));
		w57.LeftAttach = ((uint)(1));
		w57.RightAttach = ((uint)(2));
		w57.XOptions = ((global::Gtk.AttachOptions)(4));
		w57.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox2.Add (this.table5);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.table5]));
		w58.Position = 0;
		w58.Expand = false;
		w58.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.drawingarea1 = new global::Gtk.DrawingArea ();
		this.drawingarea1.Name = "drawingarea1";
		this.vbox2.Add (this.drawingarea1);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.drawingarea1]));
		w59.Position = 1;
		this.GtkAlignment4.Add (this.vbox2);
		this.frame5.Add (this.GtkAlignment4);
		this.GtkLabel6 = new global::Gtk.Label ();
		this.GtkLabel6.Name = "GtkLabel6";
		this.GtkLabel6.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Ergebnis</b>");
		this.GtkLabel6.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel6;
		this.vbox1.Add (this.frame5);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.frame5]));
		w62.Position = 5;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w63 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w63.Position = 6;
		w63.Expand = false;
		w63.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 507;
		this.DefaultHeight = 661;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.quitAction.Activated += new global::System.EventHandler (this.OnQuitActionActivated);
		this.loadButton.Clicked += new global::System.EventHandler (this.OnLoadButtonClicked);
		this.szenario_endscale.ChangeValue += new global::Gtk.ChangeValueHandler (this.OnSzenarioEndscaleChangeValue);
		this.szenario_end.Changed += new global::System.EventHandler (this.OnSzenarioEndChanged);
	}
}
